# Generated by Django 2.1.1 on 2018-09-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_one', '0003_auto_20180926_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_add', models.ManyToManyField(related_name='item_by_users', to='app_one.User')),
                ('item_created', models.ForeignKey(on_delete='models.CASCADE', related_name='item_created', to='app_one.User')),
            ],
        ),
    ]
