# Generated by Django 2.1.1 on 2018-09-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_one', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_add',
        ),
    ]
