# Generated by Django 2.1.1 on 2018-09-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_one', '0002_remove_item_item_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_created',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='user_created', to='app_one.User'),
        ),
    ]
